name       : freecad
version    : 0.19.4
release    : 3
source     :
    - https://github.com/FreeCAD/FreeCAD/archive/refs/tags/0.19.4.tar.gz : e40a1c343956e13c56cc8578d025ae83d68d9d20acda1732953bc8a3883e9722
homepage   : https://www.freecadweb.org/
license    : LGPL-2.0-or-later
component  : office
summary    : FreeCAD 3D parametric modeler
description: |
    FreeCAD is an open-source parametric 3D modeler made primarily to design real-life objects of any size. Parametric modeling allows you to easily modify your design by going back into your model history to change its parameters. FreeCAD lets you to sketch geometry constrained 2D shapes and use them as a base to build other objects. It contains many components to adjust dimensions or extract design details from 3D models to create high quality production-ready drawings. FreeCAD is designed to fit a wide range of uses including product design, mechanical engineering and architecture, whether you are a hobbyist, programmer, experienced CAD user, student or teacher.
clang      : yes
builddeps  :
    - pkgconfig(Coin)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(SoQt)
    - pkgconfig(eigen3)
    - pkgconfig(fontconfig)
    - pkgconfig(gts)
    - pkgconfig(jsoncpp)
    - pkgconfig(netcdf)
    - pkgconfig(opencv4)
    - pkgconfig(pcl_io)
    - pkgconfig(pyside2)
    - pkgconfig(xerces-c)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - VTK-devel
    - matplotlib
    - med-c-devel
    - opencascade-devel
    - pybind11
    - python-cparser
    - python-pivy
    - python-pyside2-tools
    - swig
rundeps    :
    - matplotlib
    - python-cparser
    - python-pivy
setup      : |
    %apply_patches
    %patch -p1 --binary -i $pkgfiles/part-port-to-occt-7_6_0.patch

    IFS=
    %cmake_ninja \
        -DBUILD_ENABLE_CXX_STD=C++17 \
        -DBoost_NO_BOOST_CMAKE=ON \
        -DCMAKE_INSTALL_PREFIX=/usr/lib64/freecad \
        -DCMAKE_INSTALL_DATADIR=/usr/share/freecad \
        -DCMAKE_INSTALL_DATAROOTDIR=/usr/share \
        -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/freecad \
        -DBUILD_CLOUD=ON \
        -DBUILD_FLAT_MESH=ON \
        -DBUILD_PLOT=ON \
        -DBUILD_QT5=ON \
        -DOpenGL_GL_PREFERENCE=LEGACY \
        -DFREECAD_USE_EXTERNAL_PIVY=ON \
        -DFREECAD_USE_EXTERNAL_SMESH=OFF \
        -DFREECAD_USE_FREETYPE=ON \
        -DFREECAD_USE_OCC_VARIANT="Official Version" \
        -DFREECAD_USE_PCL=ON \
        -DFREECAD_USE_PYBIND11=ON \
        -DFREECAD_USE_QT_FILEDIALOG=ON \
        -DFREECAD_USE_QTWEBMODULE="Qt WebEngine" \
        -DPYTHON_EXECUTABLE=/usr/bin/python3
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile

    install -Dm00755 src/Tools/freecad-thumbnailer $installdir/usr/bin/freecad-thumbnailer
    ln -s ../lib64/freecad/bin/FreeCAD $installdir/usr/bin/FreeCAD
    ln -s ../lib64/freecad/bin/FreeCADCmd $installdir/usr/bin/FreeCADCmd

    rm -rf $installdir/usr/share/doc
